### ISSUE TITLE
intl/regress-9812.js  test case failed on hifive.

### ISSUE THREAD

**Issue by luyahan** [v8-riscv/v8#112]
**Describe the bug**
A case in intl failed on hifive.

**To Reproduce**
1. Build with options 'riscv64.release'
2. Run test/program 'riscv64.native.release/d8 --test test/intl/assert.js test/intl/utils.js test/intl/regress-9812.js --random-seed=2057794159 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --allow-natives-syntax'
3. See error

**Expected behavior**
No error occurs.

**Errors/Logs**
```
yahan@fedora-riscv-sifive:~ $ python2 ./tools/run-tests.py --outdir=./riscv64.native.release/  intl | tee log-intl.txt
Build found: /home/yahan/./riscv64.native.release
>>> Running tests for riscv64.debug
>>> Running with test processors
=== intl/regress-9812 ===                   ^Bd
Warning: unknown flag --enable-slow-asserts.
Try --help for options
366
/home/yahan/test/intl/assert.js:105: Error: Failure (Using Intl.DateFormat formatRange with en-001-u-ca-islamic should not throw): expected <no expection>, found <exception: TypeError: Internal error. Icu error.>.
  throw new Error(message);
  ^
Error: Failure (Using Intl.DateFormat formatRange with en-001-u-ca-islamic should not throw): expected <no expection>, found <exception: TypeError: Internal error. Icu error.>.
    at fail (/home/yahan/test/intl/assert.js:105:9)
    at assertDoesNotThrow (/home/yahan/test/intl/assert.js:182:5)
    at /home/yahan/test/intl/regress-9812.js:61:5
    at Array.forEach (<anonymous>)
    at /home/yahan/test/intl/regress-9812.js:59:11
    at Array.forEach (<anonymous>)
    at /home/yahan/test/intl/regress-9812.js:58:11
Command: riscv64.native.release/d8 --test test/intl/assert.js test/intl/utils.js test/intl/regress-9812.js --random-seed=2057794159 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --allow-natives-syntax
[02:11|%  96|+ 217|-   1]: Done
>>> 225 base tests produced 218 (96%) non-filtered tests
>>> 218 tests ran
```

**Additional context**

**Comment by luyahan** [comment]
```
calendars.forEach(function(calendar) {
  locales.forEach(function(baseLocale) {
    let locale = `${baseLocale}-u-ca-${calendar}`;
    console.log(locale);
    let f = new Intl.DateTimeFormat(locale);
    let r = f.formatRange(d1,d2);
    console.log(r);
    assertDoesNotThrow(
        () => (new Intl.DateTimeFormat(locale)).formatRange(d1, d2),
        `Using Intl.DateFormat formatRange with ${locale} should not throw`);
  })
})
```
log:
```
Try --help for options
cs-u-ca-islamic
366
29. 7. 1440 _ 3. 10. 1440 AH
cs-CZ-u-ca-islamic
29. 7. 1440 _ 3. 10. 1440 AH
en-001-u-ca-islamic
test/intl/regress-9812.js:63: TypeError: Internal error. Icu error.
    let r = f.formatRange(d1,d2);
              ^
TypeError: Internal error. Icu error.
    at DateTimeFormat.formatRange (<anonymous>)
    at test/intl/regress-9812.js:63:15
    at Array.forEach (<anonymous>)
    at test/intl/regress-9812.js:59:11
    at Array.forEach (<anonymous>)
    at test/intl/regress-9812.js:58:11
```

**Comment by luyahan** [comment]
ICU c++ code error, U_MISSING_RESOURCE_ERROR.
It should be missing some file.
