### ISSUE TITLE
[RISCV64 Branch][Hifive unleashed Borad] mjsunit/regress/wasm/regress-1010272 failed

### ISSUE THREAD

**Issue by luyahan** [v8-riscv/v8#178]
**Describe the bug**

**To Reproduce**
1. Build with options `riscv64.native.debug`
2. Run test/program `riscv64.native/d8 --test test/mjsunit/mjsunit.js test/mjsunit/regress/wasm/regress-1010272.js --random-seed=-652826751 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --wasm-grow-shared-memory --experimental-wasm-threads`
3. See error

**Expected behavior**

**Errors/Logs**
```
=== mjsunit/regress/wasm/regress-1010272 ===
Warning: unknown flag --enable-slow-asserts.
Try --help for options
/home/luyahan/test/mjsunit/regress/wasm/regress-1010272.js:11: RangeError: WebAssembly.Memory(): could not allocate memory
  return new WebAssembly.Memory({initial : initial, maximum : maximum, shared : true});
         ^
RangeError: WebAssembly.Memory(): could not allocate memory
    at AllocMemory (/home/luyahan/test/mjsunit/regress/wasm/regress-1010272.js:11:10)
    at RunTest (/home/luyahan/test/mjsunit/regress/wasm/regress-1010272.js:25:18)
    at /home/luyahan/test/mjsunit/regress/wasm/regress-1010272.js:30:3
Command: riscv64.native/d8 --test test/mjsunit/mjsunit.js test/mjsunit/regress/wasm/regress-1010272.js --random-seed=-652826751 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --wasm-grow-shared-memory --experimental-wasm-threads
--- FAILED ---
```

**Additional context**

**Comment by luyahan** [comment]
Can't allocate so many memory like regress-1010272.js. so can ignore it on hifive board.
