### ISSUE TITLE
Test fail: intl/regress-1074578

### ISSUE THREAD

**Issue by qjivy** [v8-riscv/v8#304]
**Describe the bug**
This failure happens when I verify the riscv64 branch using ./v8-riscv-tools/test-riscv.sh under riscv64.sim build.

**To Reproduce**

1. Build with options 

The  args.gn is as following:
```
is_component_build` = false
is_debug = true
target_cpu = "x64"
v8_target_cpu = "riscv64"
use_goma = false
goma_dir = "None"
```
2. Run test/program 

```
./out/riscv64.sim/d8 --test /home/qjivy/work/v8/v8/test/intl/assert.js /home/qjivy/work/v8/v8/test/intl/utils.js /home/qjivy/work/v8/v8/test/intl/regress-1074578.js --random-seed=1819417120 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --allow-natives-syntax
```

3. See error

```
Warning: unknown flag --enable-slow-asserts.
Try --help for options
/home/qjivy/work/v8/v8/test/intl/assert.js:105: Error: Failure: expected <March 8, 2020 at 5:00:00 PM MST>, found <March 8, 2020 at 5:00:00 PM PDT>.
  throw new Error(message);
  ^
Error: Failure: expected <March 8, 2020 at 5:00:00 PM MST>, found <March 8, 2020 at 5:00:00 PM PDT>.
    at fail (/home/qjivy/work/v8/v8/test/intl/assert.js:105:9)
    at assertEquals (/home/qjivy/work/v8/v8/test/intl/assert.js:114:5)
    at /home/qjivy/work/v8/v8/test/intl/regress-1074578.js:34:1
```

**Expected behavior**
It should pass.

**Errors/Logs**
As pasted above.

**Additional context**

**Comment by fw-brice** [comment]
I cannot reproduce this error.

**Comment by qjivy** [comment]
Hi, Brice, do I need to provide more information, such as build platform for this issue? I just pull the latest code and build, the errors still happens.
Since it's the first time I take these tests, I don't quite sure if I had some misunderstandings about the build and test process.
I just notice that this error also happens on a x64.release build.

With args.gn
```
is_component_build = false
is_debug = false
target_cpu = "x64"
use_goma = false
goma_dir = "None"
v8_enable_backtrace = true
v8_enable_disassembler = true
v8_enable_object_print = true
v8_enable_verify_heap = true
```

The testing command line:

```
./out/x64.release/d8 --test /home/qjivy/work/v8/v8/test/intl/assert.js /home/qjivy/work/v8/v8/test/intl/utils.js /home/qjivy/work/v8/v8/test/intl/regress-1074578.js --random-seed=1819417120 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --allow-natives-syntax
```

The error info:

```
Warning: unknown flag --enable-slow-asserts.
Try --help for options
/home/qjivy/work/v8/v8/test/intl/assert.js:105: Error: Failure: expected <March 8, 2020 at 5:00:00 PM MST>, found <March 8, 2020 at 5:00:00 PM PDT>.
  throw new Error(message);
  ^
Error: Failure: expected <March 8, 2020 at 5:00:00 PM MST>, found <March 8, 2020 at 5:00:00 PM PDT>.
    at fail (/home/qjivy/work/v8/v8/test/intl/assert.js:105:9)
    at assertEquals (/home/qjivy/work/v8/v8/test/intl/assert.js:114:5)
    at /home/qjivy/work/v8/v8/test/intl/regress-1074578.js:34:1
```

**Comment by fw-brice** [comment]
I'm not sure what might be wrong. These tests pass for the riscv64.sim build in the CI job as well. I do not see the error in my x64.release build either. Could someone else please try these tests to help determine which one of us has something going wrong in the build?

**Comment by lazyparser** [comment]
```
wuwei@plct-build-5:~/v8riscv/v8$ ./out/riscv64.sim.debug/d8 --test /home/wuwei/v8riscv/v8/test/intl/assert.js /home/wuwei/v8riscv/v8/test/intl/utils.js /home/wuwei/v8riscv/v8/test/intl/regress-1074578.js --random-seed=1819417120 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --allow-natives-syntax
Warning: unknown flag --enable-slow-asserts.
Try --help for options
wuwei@plct-build-5:~/v8riscv/v8$
```

I have not reproduced either.

by looking at the error message, it could be a timezone regression issue.

the testcase was added by

```
wuwei@plct-build-5:~/v8riscv/v8/test/intl$ git log --  regress-1074578.js
commit 2a0505eda980830f7c2aa83dba0728e0ea20fcc1
Author: Frank Tang <ftang@chromium.org>
Date:   Wed Apr 29 16:33:56 2020 -0700

    Roll ICU to tz2020a on top of 65.1

    Somehow the auto rolling of ICU does not happen after 2020/3/24
    (see https://bugs.chromium.org/p/v8/issues/detail?id=10481) so I hand roll
    ICU now.

    For example, the following icu hash into chrome/src/DEPS was not yet
    auto rolled after ~4 weeks:
    2020/4/1 https://chromium-review.googlesource.com/c/chromium/src/+/2109133
    2020/4/28 https://chromium-review.googlesource.com/c/chromium/src/+/2162266

    Bug: chromium:1074578
    Change-Id: I7ba0d240351f7458997e66a1e580564684a8b5a2
    Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/2173670
    Reviewed-by: Shu-yu Guo <syg@chromium.org>
    Commit-Queue: Frank Tang <ftang@chromium.org>
    Cr-Commit-Position: refs/heads/master@{#67485}
```

**Comment by qjivy** [comment]
@lazyparser  Thanks!  Could you please also try for #305 ? 
Let me find what happens in my build.

**Comment by qjivy** [comment]
It relates to some old third party repo which could be updated by gclient sync.
After update, the #304, #305, #306, #307  can't be reproduced any longer. 
So I close them.
