### ISSUE TITLE
Test fail: intl/number-format/unified/percent

### ISSUE THREAD

**Issue by qjivy** [v8-riscv/v8#305]
**Describe the bug**

This failure happens when I verify the riscv64 branch using ./v8-riscv-tools/test-riscv.sh under riscv64.sim build.

**To Reproduce**
1. Build with options 

The  args.gn is as following:
```
is_component_build` = false
is_debug = true
target_cpu = "x64"
v8_target_cpu = "riscv64"
use_goma = false
goma_dir = "None"
```

2. Run test/program 

```
./out/riscv64.sim/d8 --test /home/qjivy/work/v8/v8/test/intl/assert.js /home/qjivy/work/v8/v8/test/intl/utils.js /home/qjivy/work/v8/v8/test/intl/number-format/unified/percent.js --random-seed=1819417120 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner –allow-natives-syntax
```

3. See error

```
--- stdout ---
Warning: unknown flag --enable-slow-asserts.
Try --help for options
/home/qjivy/work/v8/v8/test/intl/assert.js:105: Error: Failure: expected <percent>, found <decimal>.
  throw new Error(message);
  ^
Error: Failure: expected <percent>, found <decimal>.
    at fail (/home/qjivy/work/v8/v8/test/intl/assert.js:105:9)
    at assertEquals (/home/qjivy/work/v8/v8/test/intl/assert.js:114:5)
    at /home/qjivy/work/v8/v8/test/intl/number-format/unified/percent.js:13:1
```
**Expected behavior**
It should pass.

**Errors/Logs**

As mentioned above.

**Additional context**

It's a bug of "Assert". It seems like a  data type error. And perhaps it's a same type bug as #304 
**v8/test/intl/assert.js:105: Error: Failure: expected <percent>, found <decimal>.**

**Comment by fw-brice** [comment]
I can't reproduce this failure.

**Comment by lazyparser** [comment]
test result:

```
wuwei@plct-build-5:~/v8riscv/v8$ ./out/riscv64.sim.debug/d8 --test /home/wuwei/v8riscv/v8/test/intl/assert.js /home/wuwei/v8riscv/v8/test/intl/utils.js /home/wuwei/v8riscv/v8/test/intl/number-format/unified/percent.js --random-seed=1819417120 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner –allow-natives-syntax
Warning: unknown flag --enable-slow-asserts.
Try --help for options
Error reading '–allow-natives-syntax'
wuwei@plct-build-5:~/v8riscv/v8$ cat out/riscv64.sim.debug/args.gn
is_component_build = false
is_debug = true
target_cpu = "x64"
v8_target_cpu = "riscv64"
use_goma = false
goma_dir = "None"
```

**Comment by lazyparser** [comment]
```
wuwei@plct-build-5:~/v8riscv/v8$ ./out/riscv64.sim.debug/d8 --test /home/wuwei/v8riscv/v8/test/intl/assert.js /home/wuwei/v8riscv/v8/test/intl/utils.js /home/wuwei/v8riscv/v8/test/intl/number-format/unified/percent.js --random-seed=1819417120 --nohard-abort --verify-heap --testing-d8-test-runner --allow-natives-syntax
wuwei@plct-build-5:~/v8riscv/v8$ echo $?
0
wuwei@plct-build-5:~/v8riscv/v8$
```

**Comment by qjivy** [comment]
It relates to some old third party repo which could be updated by gclient sync.
After update, the #304, #305, #306, #307  can't be reproduced any longer. 
So I close them.
