### ISSUE TITLE
Test fail: intl/number-format/unified/unit-display

### ISSUE THREAD

**Issue by qjivy** [v8-riscv/v8#307]
**Describe the bug**

This failure happens when I verify the riscv64 branch using ./v8-riscv-tools/test-riscv.sh under riscv64.sim build.

**To Reproduce**
1. Build with options 

The  args.gn is as following:
```
is_component_build` = false
is_debug = true
target_cpu = "x64"
v8_target_cpu = "riscv64"
use_goma = false
goma_dir = "None"
```

2. Run test/program 

```
./out/riscv64.sim/d8 --test /home/qjivy/work/v8/v8/test/intl/assert.js /home/qjivy/work/v8/v8/test/intl/utils.js /home/qjivy/work/v8/v8/test/intl/number-format/unified/unit-display.js --random-seed=1819417120 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --allow-natives-syntax
```

3. See error

```
--- stdout ---
Warning: unknown flag --enable-slow-asserts.
Try --help for options
/home/qjivy/work/v8/v8/test/intl/assert.js:105: Error: Failure: expected <short>, found <undefined>.
  throw new Error(message);
  ^
Error: Failure: expected <short>, found <undefined>.
    at fail (/home/qjivy/work/v8/v8/test/intl/assert.js:105:9)
    at assertEquals (/home/qjivy/work/v8/v8/test/intl/assert.js:114:5)
    at /home/qjivy/work/v8/v8/test/intl/number-format/unified/unit-display.js:19:1
```
**Expected behavior**
It should pass.

**Errors/Logs**

As mentioned above.

**Additional context**
It may be a duplicate bug as #304, #305, #306.

**Comment by fw-brice** [comment]
I cannot reproduce this failure.

**Comment by qjivy** [comment]
It relates to some old third party repo which could be updated by gclient sync.
After update, the #304, #305, #306, #307  can't be reproduced any longer. 
So I close them.
