### ISSUE TITLE
wasm-spec-tests/proposals/js-types/exports and imports fail

### ISSUE THREAD

**Issue by fw-brice** [v8-riscv/v8#403]
**Describe the bug**
Two tests fail with the latest rebased branch:
* wasm-spec-tests/proposals/js-types/exports
* wasm-spec-tests/proposals/js-types/imports

**To Reproduce**
1. Checkout 'rebase-to-master':
  ```
  git checkout rebase-to-master
  ```
2. Build:
  ```
  ./tools/dev/gm.py riscv64.debug.all
  ```
3. Run tests:
   ```
   out/riscv64.debug/d8 --test test/wasm-spec-tests/tests/proposals/js-types/exports.js --random-seed=-157172359 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --experimental-wasm-type-reflection --wasm-staging

   out/riscv64.debug/d8 --test test/wasm-spec-tests/tests/proposals/js-types/imports.js --random-seed=-157172359 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --experimental-wasm-type-reflection --wasm-staging
   ```

**Expected behavior**
These tests should pass.

**Errors/Logs**
```
#15 5293. === wasm-spec-tests/proposals/js-types/exports ===
#15 5293. Command: /v8/out/riscv64.debug/d8 --test /v8/test/wasm-spec-tests/tests/proposals/js-types/exports.js --random-seed=-157172359 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --experimental-wasm-type-reflection --wasm-staging
#15 5293. === wasm-spec-tests/proposals/js-types/imports ===
#15 5293. --- stdout ---
#15 5293. 13
#15 5293. 14 42
#15 5293. 13
#15 5293. 13
#15 5293. 13
#15 5293. 13
#15 5293. 25 53
#15 5293. 24
#15 5293. 24
#15 5293. 24
#15 5293. /v8/test/wasm-spec-tests/tests/proposals/js-types/imports.js:78: Error: Wasm validation failure expected
#15 5293.   throw new Error("Wasm validation failure expected");
#15 5293.   ^
#15 5293. Error: Wasm validation failure expected
#15 5293.     at assert_invalid (/v8/test/wasm-spec-tests/tests/proposals/js-types/imports.js:78:9)
#15 5293.     at /v8/test/wasm-spec-tests/tests/proposals/js-types/imports.js:336:1
#15 5293. Command: /v8/out/riscv64.debug/d8 --test /v8/test/wasm-spec-tests/tests/proposals/js-types/imports.js --random-seed=-157172359 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --experimental-wasm-type-reflection --wasm-staging
#15 5293. 
#15 5293. ===
#15 5293. === 2 tests failed
#15 5293. ===
```

**Comment by qjivy** [comment]
Retry these two case on the riscv-sparkplug-dev branch with commit id bc90d62 .

**exports** pass
**import** still error

**Comment by luyahan** [comment]
> Retry these two case on the riscv-sparkplug-dev branch with commit id [bc90d62](https://github.com/v8-riscv/v8/commit/bc90d624d597897733da22958593a18083bc61bf) .
> 
> **exports** pass
> **import** still error
Refer 
https://github.com/v8-riscv/v8/blob/cda7183b963712a5a65827e6c42f450b49068dc9/test/wasm-spec-tests/wasm-spec-tests.status#L23
import should be failed
